apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.service.name }}
spec:
    selector:
        app: {{ .Values.appName }}
    ports:
        - protocol: {{ .Values.service.protocol }}
          port: {{ .Values.service.port }}
          targetPort: {{ .Values.deployment.containerPort }}